version: '3.8'
services:
  #centralserver:
    #build:
      #context: ./CentralServer
      #dockerfile: Dockerfile
    #ports:
      #- "7087:443"

  manufacturinghub:
    build:
      context: ./ManufacturingHub
      dockerfile: Dockerfile
    ports:
      - "7070:443"
    depends_on:
      - nginx
      #- centralserver
    volumes:
      - blazor_wwwroot:/usr/share/nginx/html  # Ensures the files are accessible in the right location

  nginx:
    image: nginx:1.13.12-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/:/etc/nginx/
      - ./nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./nginx.key:/etc/nginx/ssl/nginx.key
      - blazor_wwwroot:/usr/share/nginx/html

volumes:
  blazor_wwwroot:  # This ensures Docker recognizes it properly
